version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: strix
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ../mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge